# Configuration for a plugin published to npm
[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="index.html"
    path = "/fr/index.html" #la racine du site

    # Configuration for a plugin published to npm
[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="index.html"
    path = "/fr/oeuvres/Autumn.html" #la racine du site

        # Configuration for a plugin published to npm
[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  [[plugins.inputs.audits]]
    output_path="index.html"
    path = "/fr/artistes/George_seeley.html" #la racine du site